name:                z85
version:             0.0.2
github:              "athanclark/z85"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "Copyright (c) 2018 Athan Clark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Implementation of the z85 binary codec
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/athanclark/z85#readme>

dependencies:
- base >= 4.8 && < 4.12
- attoparsec
- attoparsec-binary >= 0.2
- bytestring
- pipes >= 4.0 && < 4.4
- pipes-bytestring >= 2.1.6
- pipes-text >= 0.0.2.5
- QuickCheck
- text
- vector-sized

library:
  source-dirs: src

tests:
  z85-bytestring-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - z85
    - QuickCheck
    - quickcheck-instances
    - tasty
    - tasty-hunit
    - tasty-quickcheck
